# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.argocd.v1alpha1 import Application as _Resource1
    from cloudcoil.models.argocd.v1alpha1 import ApplicationSet as _Resource2
    from cloudcoil.models.argocd.v1alpha1 import AppProject as _Resource0

_MODELS = {
    ("AppProject", "argoproj.io/v1alpha1"): ("cloudcoil.models.argocd.v1alpha1", "AppProject"),
    ("AppProject", ""): ("cloudcoil.models.argocd.v1alpha1", "AppProject"),
    ("Application", "argoproj.io/v1alpha1"): ("cloudcoil.models.argocd.v1alpha1", "Application"),
    ("Application", ""): ("cloudcoil.models.argocd.v1alpha1", "Application"),
    ("ApplicationSet", "argoproj.io/v1alpha1"): (
        "cloudcoil.models.argocd.v1alpha1",
        "ApplicationSet",
    ),
    ("ApplicationSet", ""): ("cloudcoil.models.argocd.v1alpha1", "ApplicationSet"),
}


@overload
def get_model(
    kind: Literal["AppProject"], *, api_version: Literal["argoproj.io/v1alpha1"]
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["AppProject"], *, api_version: Literal[""] = ""
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["Application"], *, api_version: Literal["argoproj.io/v1alpha1"]
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["Application"], *, api_version: Literal[""] = ""
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["ApplicationSet"], *, api_version: Literal["argoproj.io/v1alpha1"]
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["ApplicationSet"], *, api_version: Literal[""] = ""
) -> type[_Resource2]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
